In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

In [2]:
ESR = pd.read_csv('user_b.csv')
ESR.head()

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,2.0,3577.872723,2067.408557,1.025738,1.744496,0.883469,1.282893,3.039058,2.730998,3568.553050,...,1.489550,2.038554,3574.021851,2064.935214,1.025629,2.865736,0.427347,1.619304,2.067162,2.244023
1,2.0,3577.830179,2066.857321,0.573598,1.711991,1.012575,1.900513,2.746218,3.066821,3569.060181,...,1.707576,2.184310,3574.324753,2065.035528,0.677875,2.216925,0.617394,1.926881,1.933766,2.339523
2,2.0,3576.706494,2066.736837,0.525896,1.584096,0.201467,1.038686,2.685631,2.977552,3569.214969,...,1.553983,2.112580,3574.523186,2064.691860,0.605963,2.000947,0.354295,1.633133,2.017921,2.507417
3,2.0,3577.453273,2066.839712,0.549982,1.322669,0.373559,1.043046,2.547650,2.906844,3568.109499,...,1.777661,2.219161,3574.218300,2064.862052,0.712377,1.407308,0.731966,1.088495,2.112044,2.416092
4,2.0,3577.145874,2066.495108,0.253211,1.169839,0.256740,1.169276,2.680609,2.864313,3568.736123,...,2.108666,2.162283,3574.278866,2065.125094,0.166225,1.150858,0.540831,1.736812,1.869272,2.461744

In [3]:
ESR

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,2.0,3577.872723,2067.408557,1.025738,1.744496,0.883469,1.282893,3.039058,2.730998,3568.553050,...,1.489550,2.038554,3574.021851,2064.935214,1.025629,2.865736,0.427347,1.619304,2.067162,2.244023
1,2.0,3577.830179,2066.857321,0.573598,1.711991,1.012575,1.900513,2.746218,3.066821,3569.060181,...,1.707576,2.184310,3574.324753,2065.035528,0.677875,2.216925,0.617394,1.926881,1.933766,2.339523
2,2.0,3576.706494,2066.736837,0.525896,1.584096,0.201467,1.038686,2.685631,2.977552,3569.214969,...,1.553983,2.112580,3574.523186,2064.691860,0.605963,2.000947,0.354295,1.633133,2.017921,2.507417
3,2.0,3577.453273,2066.839712,0.549982,1.322669,0.373559,1.043046,2.547650,2.906844,3568.109499,...,1.777661,2.219161,3574.218300,2064.862052,0.712377,1.407308,0.731966,1.088495,2.112044,2.416092
4,2.0,3577.145874,2066.495108,0.253211,1.169839,0.256740,1.169276,2.680609,2.864313,3568.736123,...,2.108666,2.162283,3574.278866,2065.125094,0.166225,1.150858,0.540831,1.736812,1.869272,2.461744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3572.565057,2063.708485,1.744637,1.988922,0.581469,1.282472,1.867422,2.188384,3568.740336,...,2.079211,1.763156,3568.455604,2061.713327,0.831698,1.906609,0.629852,1.184600,1.155996,2.077971
2876,0.0,3572.404321,2063.901193,1.018693,2.245893,0.466604,0.990731,1.713640,2.200029,3568.847030,...,2.228758,1.708778,3568.391648,2061.763619,0.680120,1.595377,0.505113,0.904035,1.295171,2.186611
2877,0.0,3572.949208,2064.434279,0.776556,2.433488,0.535157,1.423937,1.707884,2.320001,3569.545664,...,2.242820,1.806139,3568.365951,2061.777876,1.195042,1.804608,0.304676,1.209675,1.269658,2.353031
2878,0.0,3573.398949,2064.834792,0.662160,2.048126,0.430397,1.256662,1.830379,2.267566,3569.716690,...,2.252700,2.012235,3568.843386,2062.337067,1.404224,1.949056,0.546461,1.305942,1.601821,2.083668
2879,0.0,3572.213539,2064.347537,0.864426,2.109316,0.157382,1.006024,1.870390,2.278486,3569.180821,...,2.409930,1.915245,3569.610409,2061.845187,1.910545,1.845916,0.585893,0.888587,1.563359,2.100800

In [4]:
ESR.columns

Index(['Class', 'AF3 delta std', 'AF3 delta m', 'AF3 theta std', 'AF3 theta m',
       'AF3 alpha std', 'AF3 alpha m', 'AF3 beta std', 'AF3 beta m',
       'F7 delta std',
       ...
       'F8 beta std', 'F8 beta m', 'AF4 delta std', 'AF4 delta m',
       'AF4 theta std', 'AF4 theta m', 'AF4 alpha std', 'AF4 alpha m',
       'AF4 beta std', 'AF4 beta m'],
      dtype='object', length=113)

In [5]:
ESR.isnull().sum()  #isnull().sum()  gives the sum of missing value in the data set or  nan values here in the data set

Class            0
AF3 delta std    0
AF3 delta m      0
AF3 theta std    0
AF3 theta m      0
                ..
AF4 theta m      0
AF4 alpha std    0
AF4 alpha m      0
AF4 beta std     0
AF4 beta m       0
Length: 113, dtype: int64

In [6]:
ESR.info() # gives the information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Columns: 113 entries, Class to AF4 beta m
dtypes: float64(113)
memory usage: 2.5 MB

In [7]:
ESR.tail(2881) #gives the entire description of the data set

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,2.0,3577.872723,2067.408557,1.025738,1.744496,0.883469,1.282893,3.039058,2.730998,3568.553050,...,1.489550,2.038554,3574.021851,2064.935214,1.025629,2.865736,0.427347,1.619304,2.067162,2.244023
1,2.0,3577.830179,2066.857321,0.573598,1.711991,1.012575,1.900513,2.746218,3.066821,3569.060181,...,1.707576,2.184310,3574.324753,2065.035528,0.677875,2.216925,0.617394,1.926881,1.933766,2.339523
2,2.0,3576.706494,2066.736837,0.525896,1.584096,0.201467,1.038686,2.685631,2.977552,3569.214969,...,1.553983,2.112580,3574.523186,2064.691860,0.605963,2.000947,0.354295,1.633133,2.017921,2.507417
3,2.0,3577.453273,2066.839712,0.549982,1.322669,0.373559,1.043046,2.547650,2.906844,3568.109499,...,1.777661,2.219161,3574.218300,2064.862052,0.712377,1.407308,0.731966,1.088495,2.112044,2.416092
4,2.0,3577.145874,2066.495108,0.253211,1.169839,0.256740,1.169276,2.680609,2.864313,3568.736123,...,2.108666,2.162283,3574.278866,2065.125094,0.166225,1.150858,0.540831,1.736812,1.869272,2.461744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3572.565057,2063.708485,1.744637,1.988922,0.581469,1.282472,1.867422,2.188384,3568.740336,...,2.079211,1.763156,3568.455604,2061.713327,0.831698,1.906609,0.629852,1.184600,1.155996,2.077971
2876,0.0,3572.404321,2063.901193,1.018693,2.245893,0.466604,0.990731,1.713640,2.200029,3568.847030,...,2.228758,1.708778,3568.391648,2061.763619,0.680120,1.595377,0.505113,0.904035,1.295171,2.186611
2877,0.0,3572.949208,2064.434279,0.776556,2.433488,0.535157,1.423937,1.707884,2.320001,3569.545664,...,2.242820,1.806139,3568.365951,2061.777876,1.195042,1.804608,0.304676,1.209675,1.269658,2.353031
2878,0.0,3573.398949,2064.834792,0.662160,2.048126,0.430397,1.256662,1.830379,2.267566,3569.716690,...,2.252700,2.012235,3568.843386,2062.337067,1.404224,1.949056,0.546461,1.305942,1.601821,2.083668
2879,0.0,3572.213539,2064.347537,0.864426,2.109316,0.157382,1.006024,1.870390,2.278486,3569.180821,...,2.409930,1.915245,3569.610409,2061.845187,1.910545,1.845916,0.585893,0.888587,1.563359,2.100800

In [8]:
ESR.loc[3] # it fetches the particular row  loc[row number]

Class               2.000000
AF3 delta std    3577.453273
AF3 delta m      2066.839712
AF3 theta std       0.549982
AF3 theta m         1.322669
                    ...
AF4 theta m         1.407308
AF4 alpha std       0.731966
AF4 alpha m         1.088495
AF4 beta std        2.112044
AF4 beta m          2.416092
Name: 3, Length: 113, dtype: float64

In [9]:
ESR.loc[3,"AF3 delta std"]

3577.453273074851

In [10]:
ESR.loc[0:4] # to extract the particular portion of the data set

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,2.0,3577.872723,2067.408557,1.025738,1.744496,0.883469,1.282893,3.039058,2.730998,3568.553050,...,1.489550,2.038554,3574.021851,2064.935214,1.025629,2.865736,0.427347,1.619304,2.067162,2.244023
1,2.0,3577.830179,2066.857321,0.573598,1.711991,1.012575,1.900513,2.746218,3.066821,3569.060181,...,1.707576,2.184310,3574.324753,2065.035528,0.677875,2.216925,0.617394,1.926881,1.933766,2.339523
2,2.0,3576.706494,2066.736837,0.525896,1.584096,0.201467,1.038686,2.685631,2.977552,3569.214969,...,1.553983,2.112580,3574.523186,2064.691860,0.605963,2.000947,0.354295,1.633133,2.017921,2.507417
3,2.0,3577.453273,2066.839712,0.549982,1.322669,0.373559,1.043046,2.547650,2.906844,3568.109499,...,1.777661,2.219161,3574.218300,2064.862052,0.712377,1.407308,0.731966,1.088495,2.112044,2.416092
4,2.0,3577.145874,2066.495108,0.253211,1.169839,0.256740,1.169276,2.680609,2.864313,3568.736123,...,2.108666,2.162283,3574.278866,2065.125094,0.166225,1.150858,0.540831,1.736812,1.869272,2.461744

In [11]:
ESR.loc[0:4,"AF3 delta std"] # to extract only the values of particular  section of the data set and particular coloum

0    3577.872723
1    3577.830179
2    3576.706494
3    3577.453273
4    3577.145874
Name: AF3 delta std, dtype: float64

In [12]:
ESR.loc[0:4,["AF3 delta std","AF3 delta m"]] # to extend the coloums

   AF3 delta std  AF3 delta m
0    3577.872723  2067.408557
1    3577.830179  2066.857321
2    3576.706494  2066.736837
3    3577.453273  2066.839712
4    3577.145874  2066.495108

In [13]:
# for the slicing the coloums based on the names
ESR.loc[0:4,"AF3 delta std":"AF3 alpha m"] # to extend the coloums

,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m
0,3577.872723,2067.408557,1.025738,1.744496,0.883469,1.282893
1,3577.830179,2066.857321,0.573598,1.711991,1.012575,1.900513
2,3576.706494,2066.736837,0.525896,1.584096,0.201467,1.038686
3,3577.453273,2066.839712,0.549982,1.322669,0.373559,1.043046
4,3577.145874,2066.495108,0.253211,1.169839,0.256740,1.169276

In [14]:
ESR.iloc[:,1] # iloc[rows,coloums]

0       3577.872723
1       3577.830179
2       3576.706494
3       3577.453273
4       3577.145874
           ...
2875    3572.565057
2876    3572.404321
2877    3572.949208
2878    3573.398949
2879    3572.213539
Name: AF3 delta std, Length: 2880, dtype: float64

In [15]:
l = [1,2,3,4]
l[:3]

[1, 2, 3]

In [16]:
x = ESR.iloc[:,1:113].values #take the values of the x to train
x
x.shape

(2880, 112)

In [17]:
y = ESR.iloc[:,0].values
y
y.shape
y

array([2., 2., 2., ..., 0., 0., 0.])

In [18]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state=0)

In [19]:
X_train

array([[3.57340350e+03, 2.06518977e+03, 2.05824402e+00, ...,
        2.17928352e+00, 1.56018428e+00, 2.09847941e+00],
       [3.57304660e+03, 2.06484009e+03, 9.05055687e-01, ...,
        2.97684218e+00, 1.71714497e+00, 2.15386003e+00],
       [3.57514274e+03, 2.06503001e+03, 6.90462817e-01, ...,
        1.62309532e+00, 1.57322487e+00, 2.35142750e+00],
       ...,
       [3.57390338e+03, 2.06500965e+03, 3.92493844e-01, ...,
        1.89187821e+00, 1.73111341e+00, 2.68420789e+00],
       [3.57089842e+03, 2.06343486e+03, 1.69349505e+00, ...,
        2.63136446e+00, 1.33054191e+00, 2.27014303e+00],
       [3.57091694e+03, 2.06327181e+03, 3.33702915e-01, ...,
        1.47879832e+00, 1.71838000e+00, 2.10682950e+00]])

In [20]:
X_test

array([[3.57204405e+03, 2.06495903e+03, 1.15471141e+00, ...,
        2.74057181e+00, 1.11491521e+00, 2.06879760e+00],
       [3.57360004e+03, 2.06537865e+03, 1.08487710e+00, ...,
        1.44520383e+00, 1.68566192e+00, 2.31085644e+00],
       [3.57006935e+03, 2.06282952e+03, 1.65061114e+00, ...,
        1.30525225e+00, 1.66466594e+00, 1.93301465e+00],
       ...,
       [3.57263016e+03, 2.06432145e+03, 5.70717375e-01, ...,
        1.50408708e+00, 2.28738973e+00, 2.80592007e+00],
       [3.57235870e+03, 2.06540157e+03, 7.83035201e-01, ...,
        2.49938190e+00, 1.38558324e+00, 2.11269667e+00],
       [3.56620153e+03, 2.06081937e+03, 7.33587314e-01, ...,
        1.95977721e+00, 1.45140189e+00, 1.99392338e+00]])

In [21]:
y_test

array([2., 0., 2., ..., 0., 1., 1.])

In [22]:
y_train

array([2., 1., 2., ..., 1., 1., 0.])

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# logistic regression

In [24]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression()
clf1.fit(X_train, y_train)
y_pred_log_reg = clf1.predict(X_test)
acc_log_reg = round(clf1.score(X_train, y_train) * 100, 2)
print (str(acc_log_reg) + ' %')
# Set regularization rate
reg = 1
# train a logistic regression model on the training set
model0 = LogisticRegression(C=0.1/reg, solver="liblinear").fit(X_train, y_train)
print (model0)
predictions0 = model0.predict(X_test)
print('Predicted labels: ', predictions0)
print('Actual labels:    ' ,y_test)
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions0)*100,'%')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

71.59 %
LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
Predicted labels:  [2. 2. 2. ... 0. 2. 1.]
Actual labels:     [2. 0. 2. ... 0. 1. 1.]
Accuracy: 63.802083333333336 %

# support vector machines

In [25]:
#Support Vector Machine (SVM)
from sklearn.svm import SVC
clf2 = SVC()
clf2.fit(X_train, y_train)
y_pred_svc = clf2.predict(X_test)
acc_svc = round(clf2.score(X_train, y_train) * 100, 2)
print ('Accuracy due to svm',str(acc_svc) + '%')
#acc_svc =str(acc_svc )
# Set regularization rate
reg = 1
# train a support vector machine model on the training set
svm = SVC(kernel= 'linear', random_state=1, C=0.1)
svm.fit(X_train, y_train)
print (svm)
predictions1 = svm.predict(X_test)
print('Predicted labels: ', predictions1)
print('Actual labels:    ' ,y_test)
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions1)*100,'%')

Accuracy due to svm 95.43%
SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=1,
    shrinking=True, tol=0.001, verbose=False)
Predicted labels:  [0. 2. 2. ... 0. 2. 1.]
Actual labels:     [2. 0. 2. ... 0. 1. 1.]
Accuracy: 65.10416666666666 %

# k nearest neighbors

In [26]:
#k-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
clf3 = KNeighborsClassifier()
clf3.fit(X_train, y_train)
y_pred_knn = clf3.predict(X_test)
acc_knn = round(clf3.score(X_train, y_train) * 100, 2)
print ('accuracy due to k-nearest neighbors',str(acc_knn)+'%')
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
predictions2 =classifier.predict(X_test)
print('Predicted labels: ', predictions2)
print('Actual labels:    ' ,y_test)
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions2)*100,'%')

accuracy due to k-nearest neighbors 95.43%
Predicted labels:  [2. 0. 2. ... 0. 2. 1.]
Actual labels:     [2. 0. 2. ... 0. 1. 1.]
Accuracy: 87.5 %

# pickle model linear regression

In [27]:
#linear regression model 

import pickle
with open ('liner_model','wb') as f:
    pickle.dump(clf1,f)
    
with open('liner_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)

array([0., 2., 2., ..., 0., 2., 1.])

# joblib  model linear regression

In [28]:
import joblib

joblib.dump(clf1,'linearmodel_joblib')
lin = joblib.load('linearmodel_joblib')
lin.predict(X_test)

array([0., 2., 2., ..., 0., 2., 1.])

# pickle model support vector machine

In [29]:
import pickle
with open ('svm_model','wb') as f1:
    pickle.dump(clf2,f1)
    
with open('svm_model','rb') as f1:
    np = pickle.load(f1)
    
np.predict(X_test)

array([2., 0., 2., ..., 0., 2., 1.])

# joblib model support vector machines

In [30]:
import joblib

joblib.dump(clf2,'svmmodel_joblib')
svm = joblib.load('svmmodel_joblib')
svm.predict(X_test)

array([2., 0., 2., ..., 0., 2., 1.])

# pickle model k nearest neighbour

In [31]:


import pickle
with open ('knn_model','wb') as f:
    pickle.dump(clf3,f)
    
with open('knn_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)

array([2., 0., 2., ..., 0., 2., 1.])

# joblib model for k nearest neighbour

In [32]:
import joblib

joblib.dump(clf3,'knnmodel_joblib')
svm = joblib.load('knnmodel_joblib')
svm.predict(X_test)

array([2., 0., 2., ..., 0., 2., 1.])

In [33]:
!pip install --upgrade tabulate

Requirement already up-to-date: tabulate in c:\programdata\anaconda3\lib\site-packages (0.8.9)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000015B84F1DE08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000015B84F1DCC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000015B84F1E708>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000015B84F1B088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000015B84F1BA48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/

In [34]:
!pip install --upgrade simple_colors

Requirement already up-to-date: simple_colors in c:\programdata\anaconda3\lib\site-packages (0.1.5)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001CA1BC7DCC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001CA1BC7D5C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001CA1BC7E6C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001CA1BC7B7C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001CA1BC7BF08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/

In [35]:
# import module
from tabulate import tabulate
from simple_colors import *
# assign data
mydata = [
[black('K NEAREST NEIGHBORS','bold'),black(accuracy_score(y_test, predictions2)*100,'bold')],
[black('SUPPORT VECTOR MACHINES','bold'),black(accuracy_score(y_test, predictions1)*100,'bold')],
[black('LOGISTIC REGRESSION','bold'),black(accuracy_score(y_test, predictions0)*100,'bold')]
]

# create header

head = [(red('Classifier','bold')),(red('Accuracy(%)','bold')),'\033[1m']
'Accuracy(%)'
# display table
print(tabulate(mydata, headers=head, tablefmt="grid"))

+-------------------------+---------------+
| Classifier              |   Accuracy(%) |
+=========================+===============+
| K NEAREST NEIGHBORS     |       87.5    |
+-------------------------+---------------+
| SUPPORT VECTOR MACHINES |       65.1042 |
+-------------------------+---------------+
| LOGISTIC REGRESSION     |       63.8021 |
+-------------------------+---------------+