In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

In [2]:
ESR = pd.read_csv('user_d.csv')
ESR.head()

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3566.375438,2062.665095,1.040973,2.574824,1.376404,1.657806,0.933377,2.429998,3564.653552,...,0.991871,1.800747,3564.807696,2061.398768,1.839022,2.917284,1.095649,1.342387,1.141837,1.820216
1,1.0,3565.986713,2061.826341,1.347088,2.154989,0.904145,2.603965,1.175508,2.292886,3564.071577,...,0.852802,1.620589,3565.004893,2061.989687,1.314281,2.876174,1.178849,1.939520,0.903631,2.145510
2,1.0,3566.977885,2062.639807,1.083747,2.186981,1.155864,2.293261,1.144330,2.107225,3564.207493,...,1.075723,1.422287,3567.117563,2061.465328,1.628649,2.286765,1.591144,1.949241,1.006042,2.228659
3,1.0,3566.342634,2063.069909,1.208843,2.160716,1.143995,2.283394,1.008707,2.047132,3564.536023,...,0.696173,1.416980,3565.482402,2060.885464,1.049679,2.486281,0.684482,2.173874,0.937085,2.165614
4,1.0,3567.798629,2062.549327,1.378424,3.255706,0.795261,1.726990,0.914162,1.746653,3565.157175,...,0.743514,1.384104,3566.585859,2061.257282,1.500156,3.115490,1.235855,2.453826,0.840093,2.126146

In [3]:
ESR

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3566.375438,2062.665095,1.040973,2.574824,1.376404,1.657806,0.933377,2.429998,3564.653552,...,0.991871,1.800747,3564.807696,2061.398768,1.839022,2.917284,1.095649,1.342387,1.141837,1.820216
1,1.0,3565.986713,2061.826341,1.347088,2.154989,0.904145,2.603965,1.175508,2.292886,3564.071577,...,0.852802,1.620589,3565.004893,2061.989687,1.314281,2.876174,1.178849,1.939520,0.903631,2.145510
2,1.0,3566.977885,2062.639807,1.083747,2.186981,1.155864,2.293261,1.144330,2.107225,3564.207493,...,1.075723,1.422287,3567.117563,2061.465328,1.628649,2.286765,1.591144,1.949241,1.006042,2.228659
3,1.0,3566.342634,2063.069909,1.208843,2.160716,1.143995,2.283394,1.008707,2.047132,3564.536023,...,0.696173,1.416980,3565.482402,2060.885464,1.049679,2.486281,0.684482,2.173874,0.937085,2.165614
4,1.0,3567.798629,2062.549327,1.378424,3.255706,0.795261,1.726990,0.914162,1.746653,3565.157175,...,0.743514,1.384104,3566.585859,2061.257282,1.500156,3.115490,1.235855,2.453826,0.840093,2.126146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3572.183440,2063.784708,1.229472,2.118878,0.554802,1.531674,1.515939,2.064786,3564.057879,...,1.347489,1.589724,3568.988084,2063.376781,0.731822,1.842909,0.271320,1.235039,1.081958,2.239726
2876,0.0,3571.739312,2062.870495,1.131872,2.143829,0.600867,2.161191,1.481767,1.981241,3564.245318,...,1.269081,1.474497,3569.102041,2063.103722,0.914127,2.014998,0.249743,1.573777,1.254084,2.494333
2877,0.0,3571.184751,2063.216128,1.139433,2.066175,0.613243,2.005979,1.202326,1.918536,3564.496395,...,1.233228,1.539265,3569.136435,2063.114849,0.982602,2.111638,0.943919,1.525629,1.244487,2.555489
2878,0.0,3570.595817,2062.900476,1.013536,1.579048,0.214779,1.701602,1.314499,1.782709,3564.497194,...,1.138962,1.475072,3567.959877,2062.375466,1.036738,2.004392,1.395303,1.550127,1.095299,2.372722
2879,0.0,3570.330797,2062.512769,1.654649,1.834446,0.618655,1.475103,1.296110,1.675299,3563.138833,...,1.377477,1.619593,3568.175775,2062.192979,0.981879,1.958594,1.251051,1.478645,1.559969,2.252187

In [4]:
ESR.columns

Index(['Class', 'AF3 delta std', 'AF3 delta m', 'AF3 theta std', 'AF3 theta m',
       'AF3 alpha std', 'AF3 alpha m', 'AF3 beta std', 'AF3 beta m',
       'F7 delta std',
       ...
       'F8 beta std', 'F8 beta m', 'AF4 delta std', 'AF4 delta m',
       'AF4 theta std', 'AF4 theta m', 'AF4 alpha std', 'AF4 alpha m',
       'AF4 beta std', 'AF4 beta m'],
      dtype='object', length=113)

In [5]:
ESR.isnull().sum()  #isnull().sum()  gives the sum of missing value in the data set or  nan values here in the data set

Class            0
AF3 delta std    0
AF3 delta m      0
AF3 theta std    0
AF3 theta m      0
                ..
AF4 theta m      0
AF4 alpha std    0
AF4 alpha m      0
AF4 beta std     0
AF4 beta m       0
Length: 113, dtype: int64

In [6]:
ESR.info() # gives the information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Columns: 113 entries, Class to AF4 beta m
dtypes: float64(113)
memory usage: 2.5 MB

In [7]:
ESR.tail(2881) #gives the entire description of the data set

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3566.375438,2062.665095,1.040973,2.574824,1.376404,1.657806,0.933377,2.429998,3564.653552,...,0.991871,1.800747,3564.807696,2061.398768,1.839022,2.917284,1.095649,1.342387,1.141837,1.820216
1,1.0,3565.986713,2061.826341,1.347088,2.154989,0.904145,2.603965,1.175508,2.292886,3564.071577,...,0.852802,1.620589,3565.004893,2061.989687,1.314281,2.876174,1.178849,1.939520,0.903631,2.145510
2,1.0,3566.977885,2062.639807,1.083747,2.186981,1.155864,2.293261,1.144330,2.107225,3564.207493,...,1.075723,1.422287,3567.117563,2061.465328,1.628649,2.286765,1.591144,1.949241,1.006042,2.228659
3,1.0,3566.342634,2063.069909,1.208843,2.160716,1.143995,2.283394,1.008707,2.047132,3564.536023,...,0.696173,1.416980,3565.482402,2060.885464,1.049679,2.486281,0.684482,2.173874,0.937085,2.165614
4,1.0,3567.798629,2062.549327,1.378424,3.255706,0.795261,1.726990,0.914162,1.746653,3565.157175,...,0.743514,1.384104,3566.585859,2061.257282,1.500156,3.115490,1.235855,2.453826,0.840093,2.126146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3572.183440,2063.784708,1.229472,2.118878,0.554802,1.531674,1.515939,2.064786,3564.057879,...,1.347489,1.589724,3568.988084,2063.376781,0.731822,1.842909,0.271320,1.235039,1.081958,2.239726
2876,0.0,3571.739312,2062.870495,1.131872,2.143829,0.600867,2.161191,1.481767,1.981241,3564.245318,...,1.269081,1.474497,3569.102041,2063.103722,0.914127,2.014998,0.249743,1.573777,1.254084,2.494333
2877,0.0,3571.184751,2063.216128,1.139433,2.066175,0.613243,2.005979,1.202326,1.918536,3564.496395,...,1.233228,1.539265,3569.136435,2063.114849,0.982602,2.111638,0.943919,1.525629,1.244487,2.555489
2878,0.0,3570.595817,2062.900476,1.013536,1.579048,0.214779,1.701602,1.314499,1.782709,3564.497194,...,1.138962,1.475072,3567.959877,2062.375466,1.036738,2.004392,1.395303,1.550127,1.095299,2.372722
2879,0.0,3570.330797,2062.512769,1.654649,1.834446,0.618655,1.475103,1.296110,1.675299,3563.138833,...,1.377477,1.619593,3568.175775,2062.192979,0.981879,1.958594,1.251051,1.478645,1.559969,2.252187

In [8]:
ESR.loc[3] # it fetches the particular row  loc[row number]

Class               1.000000
AF3 delta std    3566.342634
AF3 delta m      2063.069909
AF3 theta std       1.208843
AF3 theta m         2.160716
                    ...
AF4 theta m         2.486281
AF4 alpha std       0.684482
AF4 alpha m         2.173874
AF4 beta std        0.937085
AF4 beta m          2.165614
Name: 3, Length: 113, dtype: float64

In [9]:
ESR.loc[3,"AF3 delta std"]

3566.3426340136084

In [10]:
ESR.loc[0:4] # to extract the particular portion of the data set

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3566.375438,2062.665095,1.040973,2.574824,1.376404,1.657806,0.933377,2.429998,3564.653552,...,0.991871,1.800747,3564.807696,2061.398768,1.839022,2.917284,1.095649,1.342387,1.141837,1.820216
1,1.0,3565.986713,2061.826341,1.347088,2.154989,0.904145,2.603965,1.175508,2.292886,3564.071577,...,0.852802,1.620589,3565.004893,2061.989687,1.314281,2.876174,1.178849,1.939520,0.903631,2.145510
2,1.0,3566.977885,2062.639807,1.083747,2.186981,1.155864,2.293261,1.144330,2.107225,3564.207493,...,1.075723,1.422287,3567.117563,2061.465328,1.628649,2.286765,1.591144,1.949241,1.006042,2.228659
3,1.0,3566.342634,2063.069909,1.208843,2.160716,1.143995,2.283394,1.008707,2.047132,3564.536023,...,0.696173,1.416980,3565.482402,2060.885464,1.049679,2.486281,0.684482,2.173874,0.937085,2.165614
4,1.0,3567.798629,2062.549327,1.378424,3.255706,0.795261,1.726990,0.914162,1.746653,3565.157175,...,0.743514,1.384104,3566.585859,2061.257282,1.500156,3.115490,1.235855,2.453826,0.840093,2.126146

In [11]:
ESR.loc[0:4,"AF3 delta std"] # to extract only the values of particular  section of the data set and particular coloum

0    3566.375438
1    3565.986713
2    3566.977885
3    3566.342634
4    3567.798629
Name: AF3 delta std, dtype: float64

In [12]:
ESR.loc[0:4,["AF3 delta std","AF3 delta m"]] # to extend the coloums

   AF3 delta std  AF3 delta m
0    3566.375438  2062.665095
1    3565.986713  2061.826341
2    3566.977885  2062.639807
3    3566.342634  2063.069909
4    3567.798629  2062.549327

In [13]:
# for the slicing the coloums based on the names
ESR.loc[0:4,"AF3 delta std":"AF3 alpha m"] # to extend the coloums

,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m
0,3566.375438,2062.665095,1.040973,2.574824,1.376404,1.657806
1,3565.986713,2061.826341,1.347088,2.154989,0.904145,2.603965
2,3566.977885,2062.639807,1.083747,2.186981,1.155864,2.293261
3,3566.342634,2063.069909,1.208843,2.160716,1.143995,2.283394
4,3567.798629,2062.549327,1.378424,3.255706,0.795261,1.726990

In [14]:
ESR.iloc[:,1] # iloc[rows,coloums]

0       3566.375438
1       3565.986713
2       3566.977885
3       3566.342634
4       3567.798629
           ...
2875    3572.183440
2876    3571.739312
2877    3571.184751
2878    3570.595817
2879    3570.330797
Name: AF3 delta std, Length: 2880, dtype: float64

In [15]:
l = [1,2,3,4]
l[:3]

[1, 2, 3]

In [16]:
x = ESR.iloc[:,1:113].values #take the values of the x to train
x
x.shape

(2880, 112)

In [17]:
y = ESR.iloc[:,0].values
y
y.shape
y

array([1., 1., 1., ..., 0., 0., 0.])

In [18]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state=0)

In [19]:
X_train

array([[3.56948347e+03, 2.06317915e+03, 8.99505753e-01, ...,
        2.45685374e+00, 1.01082695e+00, 2.06291849e+00],
       [3.57102871e+03, 2.06336548e+03, 7.16200015e-01, ...,
        1.75016904e+00, 1.42801823e+00, 2.26716070e+00],
       [3.57161078e+03, 2.06478178e+03, 1.11366691e+00, ...,
        1.60157938e+00, 1.40369047e+00, 2.30152309e+00],
       ...,
       [3.56752209e+03, 2.06184332e+03, 1.29892853e+00, ...,
        2.39447962e+00, 9.98580492e-01, 1.84395126e+00],
       [3.57067985e+03, 2.06274991e+03, 7.35524947e-01, ...,
        2.85278545e+00, 1.21785134e+00, 2.09177173e+00],
       [3.56994168e+03, 2.06226434e+03, 1.45519505e+00, ...,
        3.06599398e+00, 1.22725632e+00, 1.88207602e+00]])

In [20]:
X_test

array([[3.57013070e+03, 2.06368108e+03, 1.17090270e+00, ...,
        3.35548345e+00, 1.21566513e+00, 2.49579623e+00],
       [3.56939896e+03, 2.06504944e+03, 1.94064624e+00, ...,
        2.37786600e+00, 9.39785992e-01, 2.00293032e+00],
       [3.57202101e+03, 2.06358730e+03, 9.11703441e-01, ...,
        1.53098819e+00, 1.17389800e+00, 2.01753390e+00],
       ...,
       [3.57524796e+03, 2.06489313e+03, 9.57588972e-01, ...,
        1.52773057e+00, 1.17000037e+00, 2.05719369e+00],
       [3.56884074e+03, 2.06272976e+03, 1.03606088e+00, ...,
        2.85649889e+00, 1.22340762e+00, 2.34053441e+00],
       [3.56760005e+03, 2.06268673e+03, 3.08768194e-01, ...,
        2.13326867e+00, 7.09639458e-01, 1.95347267e+00]])

In [21]:
y_test

array([1., 0., 1., ..., 0., 2., 2.])

In [22]:
y_train

array([1., 2., 1., ..., 2., 2., 0.])

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# logistic regression

In [24]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression()
clf1.fit(X_train, y_train)
y_pred_log_reg = clf1.predict(X_test)
acc_log_reg = round(clf1.score(X_train, y_train) * 100, 2)
print (str(acc_log_reg) + ' %')
# Set regularization rate
reg = 1
# train a logistic regression model on the training set
model0 = LogisticRegression(C=0.1/reg, solver="liblinear").fit(X_train, y_train)
print (model0)
predictions0 = model0.predict(X_test)
print('Predicted labels: ', predictions0)
print('Actual labels:    ' ,y_test)
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions0)*100,'%')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

59.95 %
LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
Predicted labels:  [2. 0. 1. ... 0. 1. 1.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 55.81597222222222 %

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

# support vector machines

In [25]:
#Support Vector Machine (SVM)
from sklearn.svm import SVC
clf2 = SVC()
clf2.fit(X_train, y_train)
y_pred_svc = clf2.predict(X_test)
acc_svc = round(clf2.score(X_train, y_train) * 100, 2)
print ('Accuracy due to svm',str(acc_svc) + '%')
#acc_svc =str(acc_svc )
# Set regularization rate
reg = 1
# train a support vector machine model on the training set
svm = SVC(kernel= 'linear', random_state=1, C=0.1)
svm.fit(X_train, y_train)
print (svm)
predictions1 = svm.predict(X_test)
print('Predicted labels: ', predictions1)
print('Actual labels:    ' ,y_test)
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions1)*100,'%')

Accuracy due to svm 90.91%
SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=1,
    shrinking=True, tol=0.001, verbose=False)
Predicted labels:  [2. 0. 1. ... 2. 1. 1.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 55.729166666666664 %

# k nearest neighbors

In [26]:
#k-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
clf3 = KNeighborsClassifier()
clf3.fit(X_train, y_train)
y_pred_knn = clf3.predict(X_test)
acc_knn = round(clf3.score(X_train, y_train) * 100, 2)
print ('accuracy due to k-nearest neighbors',str(acc_knn)+'%')
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
predictions2 =classifier.predict(X_test)
print('Predicted labels: ', predictions2)
print('Actual labels:    ' ,y_test)
from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions2)*100,'%')

accuracy due to k-nearest neighbors 93.34%
Predicted labels:  [2. 0. 0. ... 0. 0. 2.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 83.15972222222221 %

# pickle model linear regression

In [27]:
#linear regression model 

import pickle
with open ('liner_model','wb') as f:
    pickle.dump(clf1,f)
    
with open('liner_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)

array([2., 0., 1., ..., 2., 1., 2.])

# joblib  model linear regression

In [28]:
import joblib

joblib.dump(clf1,'linearmodel_joblib')
lin = joblib.load('linearmodel_joblib')
lin.predict(X_test)

array([2., 0., 1., ..., 2., 1., 2.])

# pickle model support vector machine

In [29]:
import pickle
with open ('svm_model','wb') as f1:
    pickle.dump(clf2,f1)
    
with open('svm_model','rb') as f1:
    np = pickle.load(f1)
    
np.predict(X_test)

array([2., 0., 1., ..., 0., 0., 1.])

# joblib model support vector machines

In [30]:
import joblib

joblib.dump(clf2,'svmmodel_joblib')
svm = joblib.load('svmmodel_joblib')
svm.predict(X_test)

array([2., 0., 1., ..., 0., 0., 1.])

# pickle model k nearest neighbour

In [31]:


import pickle
with open ('knn_model','wb') as f:
    pickle.dump(clf3,f)
    
with open('knn_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)

array([2., 0., 0., ..., 0., 0., 2.])

# joblib model for k nearest neighbour

In [32]:
import joblib

joblib.dump(clf3,'knnmodel_joblib')
svm = joblib.load('knnmodel_joblib')
svm.predict(X_test)

array([2., 0., 0., ..., 0., 0., 2.])

In [33]:
!pip install --upgrade tabulate

Requirement already up-to-date: tabulate in c:\programdata\anaconda3\lib\site-packages (0.8.9)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000022544E5BA48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000022544E5BF88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000022544E5B6C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000022544E59F48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000022544E59748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/tabulate/

In [34]:
!pip install --upgrade simple_colors

Requirement already up-to-date: simple_colors in c:\programdata\anaconda3\lib\site-packages (0.1.5)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BFC04E7908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BFC164B448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BFC1649BC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BFC1649D48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BFC1649FC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/simple-colors/

In [35]:
# import module
from tabulate import tabulate
from simple_colors import *
# assign data
mydata = [
[black('K NEAREST NEIGHBORS','bold'),black(accuracy_score(y_test, predictions2)*100,'bold')],
[black('SUPPORT VECTOR MACHINES','bold'),black(accuracy_score(y_test, predictions1)*100,'bold')],
[black('LOGISTIC REGRESSION','bold'),black(accuracy_score(y_test, predictions0)*100,'bold')]
]

# create header

head = [(red('Classifier','bold')),(red('Accuracy(%)','bold')),'\033[1m']
'Accuracy(%)'
# display table
print(tabulate(mydata, headers=head, tablefmt="grid"))

+-------------------------+---------------+
| Classifier              |   Accuracy(%) |
+=========================+===============+
| K NEAREST NEIGHBORS     |       83.1597 |
+-------------------------+---------------+
| SUPPORT VECTOR MACHINES |       55.7292 |
+-------------------------+---------------+
| LOGISTIC REGRESSION     |       55.816  |
+-------------------------+---------------+