In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

In [2]:
ESR = pd.read_csv('user_a.csv')
ESR.head()

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3569.164550,2063.892754,1.673726,4.444736,0.526209,3.002088,1.425022,3.302739,3563.803888,...,45.468326,72.508750,3701.186330,2182.676835,18.192418,41.349662,16.004756,42.046467,46.280843,73.565719
1,1.0,3568.423670,2063.099248,1.897790,3.728823,1.304186,1.854353,1.366575,2.546458,3563.560922,...,36.551948,66.931186,3725.210509,2180.197439,8.820788,38.012788,19.601233,29.431054,38.559351,67.470041
2,1.0,3568.157929,2062.445859,2.798014,2.574504,1.120537,1.958819,0.982433,2.258622,3563.279981,...,40.754308,66.816547,3724.417296,2176.823208,18.159202,23.612639,14.378291,19.555084,43.210004,67.781924
3,1.0,3567.710021,2062.112673,2.181775,3.610507,0.629608,2.155876,0.856275,2.233711,3562.787801,...,38.074628,63.915386,3725.822160,2177.089059,19.737616,29.484396,15.793034,25.713513,39.250246,65.031031
4,1.0,3565.546124,2063.128867,1.685161,3.384311,0.677526,1.795798,0.927924,1.909810,3562.655091,...,35.357384,64.534645,3723.053978,2167.798335,8.429414,26.374975,14.920736,35.675266,33.901687,66.956313

In [3]:
ESR

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3569.164550,2063.892754,1.673726,4.444736,0.526209,3.002088,1.425022,3.302739,3563.803888,...,45.468326,72.508750,3701.186330,2182.676835,18.192418,41.349662,16.004756,42.046467,46.280843,73.565719
1,1.0,3568.423670,2063.099248,1.897790,3.728823,1.304186,1.854353,1.366575,2.546458,3563.560922,...,36.551948,66.931186,3725.210509,2180.197439,8.820788,38.012788,19.601233,29.431054,38.559351,67.470041
2,1.0,3568.157929,2062.445859,2.798014,2.574504,1.120537,1.958819,0.982433,2.258622,3563.279981,...,40.754308,66.816547,3724.417296,2176.823208,18.159202,23.612639,14.378291,19.555084,43.210004,67.781924
3,1.0,3567.710021,2062.112673,2.181775,3.610507,0.629608,2.155876,0.856275,2.233711,3562.787801,...,38.074628,63.915386,3725.822160,2177.089059,19.737616,29.484396,15.793034,25.713513,39.250246,65.031031
4,1.0,3565.546124,2063.128867,1.685161,3.384311,0.677526,1.795798,0.927924,1.909810,3562.655091,...,35.357384,64.534645,3723.053978,2167.798335,8.429414,26.374975,14.920736,35.675266,33.901687,66.956313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3572.820630,2064.823341,0.676923,1.620879,0.965369,2.392263,2.582266,3.185588,3565.166724,...,26.247669,13.320391,3607.467804,2089.263161,1.605773,4.247634,1.649762,2.938868,31.019482,16.648758
2876,0.0,3573.915291,2065.845542,0.860279,1.504333,0.539180,1.331165,2.533695,2.870270,3565.734750,...,26.120266,14.809811,3613.165565,2089.298802,0.643899,6.903858,1.287563,3.942647,31.546882,17.429113
2877,0.0,3574.326202,2066.031013,1.416731,2.581577,0.715012,1.307975,2.261013,2.873613,3567.582880,...,26.513829,16.084048,3615.755534,2094.482958,1.851314,5.683580,2.411642,6.355117,32.238063,19.023897
2878,0.0,3573.735788,2065.945333,1.119943,2.769816,0.455408,1.541430,1.782814,3.067384,3567.857997,...,20.049092,21.248860,3620.821019,2097.450420,5.035767,12.027902,6.441267,14.663681,24.109509,26.468254
2879,0.0,3573.982930,2065.960401,1.011062,2.696217,1.021707,2.086820,1.922342,2.675613,3568.222662,...,19.210888,22.058247,3620.970803,2096.125026,4.120981,12.124434,7.613556,12.998119,23.635052,26.581116

In [4]:
ESR.columns

Index(['Class', 'AF3 delta std', 'AF3 delta m', 'AF3 theta std', 'AF3 theta m',
       'AF3 alpha std', 'AF3 alpha m', 'AF3 beta std', 'AF3 beta m',
       'F7 delta std',
       ...
       'F8 beta std', 'F8 beta m', 'AF4 delta std', 'AF4 delta m',
       'AF4 theta std', 'AF4 theta m', 'AF4 alpha std', 'AF4 alpha m',
       'AF4 beta std', 'AF4 beta m'],
      dtype='object', length=113)

In [5]:
ESR.isnull().sum()

Class            0
AF3 delta std    0
AF3 delta m      0
AF3 theta std    0
AF3 theta m      0
                ..
AF4 theta m      0
AF4 alpha std    0
AF4 alpha m      0
AF4 beta std     0
AF4 beta m       0
Length: 113, dtype: int64

In [6]:
ESR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Columns: 113 entries, Class to AF4 beta m
dtypes: float64(113)
memory usage: 2.5 MB

In [7]:
ESR.tail(2881)

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3569.164550,2063.892754,1.673726,4.444736,0.526209,3.002088,1.425022,3.302739,3563.803888,...,45.468326,72.508750,3701.186330,2182.676835,18.192418,41.349662,16.004756,42.046467,46.280843,73.565719
1,1.0,3568.423670,2063.099248,1.897790,3.728823,1.304186,1.854353,1.366575,2.546458,3563.560922,...,36.551948,66.931186,3725.210509,2180.197439,8.820788,38.012788,19.601233,29.431054,38.559351,67.470041
2,1.0,3568.157929,2062.445859,2.798014,2.574504,1.120537,1.958819,0.982433,2.258622,3563.279981,...,40.754308,66.816547,3724.417296,2176.823208,18.159202,23.612639,14.378291,19.555084,43.210004,67.781924
3,1.0,3567.710021,2062.112673,2.181775,3.610507,0.629608,2.155876,0.856275,2.233711,3562.787801,...,38.074628,63.915386,3725.822160,2177.089059,19.737616,29.484396,15.793034,25.713513,39.250246,65.031031
4,1.0,3565.546124,2063.128867,1.685161,3.384311,0.677526,1.795798,0.927924,1.909810,3562.655091,...,35.357384,64.534645,3723.053978,2167.798335,8.429414,26.374975,14.920736,35.675266,33.901687,66.956313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3572.820630,2064.823341,0.676923,1.620879,0.965369,2.392263,2.582266,3.185588,3565.166724,...,26.247669,13.320391,3607.467804,2089.263161,1.605773,4.247634,1.649762,2.938868,31.019482,16.648758
2876,0.0,3573.915291,2065.845542,0.860279,1.504333,0.539180,1.331165,2.533695,2.870270,3565.734750,...,26.120266,14.809811,3613.165565,2089.298802,0.643899,6.903858,1.287563,3.942647,31.546882,17.429113
2877,0.0,3574.326202,2066.031013,1.416731,2.581577,0.715012,1.307975,2.261013,2.873613,3567.582880,...,26.513829,16.084048,3615.755534,2094.482958,1.851314,5.683580,2.411642,6.355117,32.238063,19.023897
2878,0.0,3573.735788,2065.945333,1.119943,2.769816,0.455408,1.541430,1.782814,3.067384,3567.857997,...,20.049092,21.248860,3620.821019,2097.450420,5.035767,12.027902,6.441267,14.663681,24.109509,26.468254
2879,0.0,3573.982930,2065.960401,1.011062,2.696217,1.021707,2.086820,1.922342,2.675613,3568.222662,...,19.210888,22.058247,3620.970803,2096.125026,4.120981,12.124434,7.613556,12.998119,23.635052,26.581116

In [8]:
ESR.loc[3]

Class               1.000000
AF3 delta std    3567.710021
AF3 delta m      2062.112673
AF3 theta std       2.181775
AF3 theta m         3.610507
                    ...
AF4 theta m        29.484396
AF4 alpha std      15.793034
AF4 alpha m        25.713513
AF4 beta std       39.250246
AF4 beta m         65.031031
Name: 3, Length: 113, dtype: float64

In [9]:
ESR.loc[3,"AF3 delta std"]

3567.7100207417207

In [10]:
ESR.loc[0:4]

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3569.164550,2063.892754,1.673726,4.444736,0.526209,3.002088,1.425022,3.302739,3563.803888,...,45.468326,72.508750,3701.186330,2182.676835,18.192418,41.349662,16.004756,42.046467,46.280843,73.565719
1,1.0,3568.423670,2063.099248,1.897790,3.728823,1.304186,1.854353,1.366575,2.546458,3563.560922,...,36.551948,66.931186,3725.210509,2180.197439,8.820788,38.012788,19.601233,29.431054,38.559351,67.470041
2,1.0,3568.157929,2062.445859,2.798014,2.574504,1.120537,1.958819,0.982433,2.258622,3563.279981,...,40.754308,66.816547,3724.417296,2176.823208,18.159202,23.612639,14.378291,19.555084,43.210004,67.781924
3,1.0,3567.710021,2062.112673,2.181775,3.610507,0.629608,2.155876,0.856275,2.233711,3562.787801,...,38.074628,63.915386,3725.822160,2177.089059,19.737616,29.484396,15.793034,25.713513,39.250246,65.031031
4,1.0,3565.546124,2063.128867,1.685161,3.384311,0.677526,1.795798,0.927924,1.909810,3562.655091,...,35.357384,64.534645,3723.053978,2167.798335,8.429414,26.374975,14.920736,35.675266,33.901687,66.956313

In [11]:
ESR.loc[0:4,"AF3 delta std"]

0    3569.164550
1    3568.423670
2    3568.157929
3    3567.710021
4    3565.546124
Name: AF3 delta std, dtype: float64

In [12]:
ESR.loc[0:4,["AF3 delta std","AF3 delta m"]]

   AF3 delta std  AF3 delta m
0    3569.164550  2063.892754
1    3568.423670  2063.099248
2    3568.157929  2062.445859
3    3567.710021  2062.112673
4    3565.546124  2063.128867

In [13]:
ESR.loc[0:4,"AF3 delta std":"AF3 alpha m"]

,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m
0,3569.164550,2063.892754,1.673726,4.444736,0.526209,3.002088
1,3568.423670,2063.099248,1.897790,3.728823,1.304186,1.854353
2,3568.157929,2062.445859,2.798014,2.574504,1.120537,1.958819
3,3567.710021,2062.112673,2.181775,3.610507,0.629608,2.155876
4,3565.546124,2063.128867,1.685161,3.384311,0.677526,1.795798

In [14]:
ESR.iloc[:,1]

0       3569.164550
1       3568.423670
2       3568.157929
3       3567.710021
4       3565.546124
           ...
2875    3572.820630
2876    3573.915291
2877    3574.326202
2878    3573.735788
2879    3573.982930
Name: AF3 delta std, Length: 2880, dtype: float64

In [15]:
l = [1,2,3,4]
l[:3]

[1, 2, 3]

In [16]:
ESR['Class'].value_counts()

1.0    960
2.0    960
0.0    960
Name: Class, dtype: int64

In [17]:
ESR.groupby('Class').mean()

,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,F7 delta m,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
Class,,,,,,,,,,,,,,,,,,,,,
0.0,3573.105047,2065.212523,1.044620,2.410871,0.913148,2.169407,2.271822,3.206166,3566.765596,2061.300548,...,29.863774,29.930458,3606.659797,2103.861382,5.959522,15.421592,6.633360,17.051315,36.534612,36.415358
1.0,3572.127749,2064.913287,1.005242,2.450213,1.002910,2.418028,2.095186,3.358045,3566.624293,2061.424659,...,30.666995,37.460582,3613.489328,2112.950185,7.718776,18.899793,8.695921,21.383254,35.540257,43.179287
2.0,3572.973840,2065.407112,1.063893,2.570677,0.933328,2.344391,2.305411,3.369704,3567.368080,2061.701201,...,31.480274,31.703433,3602.580218,2104.212301,6.375408,16.687649,6.599432,17.210985,37.418496,37.699173

In [18]:
x = ESR.drop(columns='Class',axis = 1)
y = ESR['Class']

In [19]:
x.shape

(2880, 112)

In [20]:
y.shape

(2880,)

In [21]:
x

,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,F7 delta m,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,3569.164550,2063.892754,1.673726,4.444736,0.526209,3.002088,1.425022,3.302739,3563.803888,2060.239057,...,45.468326,72.508750,3701.186330,2182.676835,18.192418,41.349662,16.004756,42.046467,46.280843,73.565719
1,3568.423670,2063.099248,1.897790,3.728823,1.304186,1.854353,1.366575,2.546458,3563.560922,2059.969372,...,36.551948,66.931186,3725.210509,2180.197439,8.820788,38.012788,19.601233,29.431054,38.559351,67.470041
2,3568.157929,2062.445859,2.798014,2.574504,1.120537,1.958819,0.982433,2.258622,3563.279981,2059.543651,...,40.754308,66.816547,3724.417296,2176.823208,18.159202,23.612639,14.378291,19.555084,43.210004,67.781924
3,3567.710021,2062.112673,2.181775,3.610507,0.629608,2.155876,0.856275,2.233711,3562.787801,2059.317489,...,38.074628,63.915386,3725.822160,2177.089059,19.737616,29.484396,15.793034,25.713513,39.250246,65.031031
4,3565.546124,2063.128867,1.685161,3.384311,0.677526,1.795798,0.927924,1.909810,3562.655091,2059.139105,...,35.357384,64.534645,3723.053978,2167.798335,8.429414,26.374975,14.920736,35.675266,33.901687,66.956313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,3572.820630,2064.823341,0.676923,1.620879,0.965369,2.392263,2.582266,3.185588,3565.166724,2059.929964,...,26.247669,13.320391,3607.467804,2089.263161,1.605773,4.247634,1.649762,2.938868,31.019482,16.648758
2876,3573.915291,2065.845542,0.860279,1.504333,0.539180,1.331165,2.533695,2.870270,3565.734750,2060.423082,...,26.120266,14.809811,3613.165565,2089.298802,0.643899,6.903858,1.287563,3.942647,31.546882,17.429113
2877,3574.326202,2066.031013,1.416731,2.581577,0.715012,1.307975,2.261013,2.873613,3567.582880,2061.445856,...,26.513829,16.084048,3615.755534,2094.482958,1.851314,5.683580,2.411642,6.355117,32.238063,19.023897
2878,3573.735788,2065.945333,1.119943,2.769816,0.455408,1.541430,1.782814,3.067384,3567.857997,2061.599242,...,20.049092,21.248860,3620.821019,2097.450420,5.035767,12.027902,6.441267,14.663681,24.109509,26.468254
2879,3573.982930,2065.960401,1.011062,2.696217,1.021707,2.086820,1.922342,2.675613,3568.222662,2061.441399,...,19.210888,22.058247,3620.970803,2096.125026,4.120981,12.124434,7.613556,12.998119,23.635052,26.581116

In [22]:
y

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
2875    0.0
2876    0.0
2877    0.0
2878    0.0
2879    0.0
Name: Class, Length: 2880, dtype: float64

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc = StandardScaler()
standardized_data = sc.fit_transform(x)

In [25]:
print(standardized_data)

[[-1.62585637 -0.84035602  1.28007215 ...  1.95249006  0.63602195
   2.44408311]
 [-1.96317524 -1.35933392  1.73118027 ...  0.90425099  0.13402758
   2.01184337]
 [-2.08416582 -1.78667094  3.54360232 ...  0.08363757  0.4363787
   2.03395875]
 ...
 [ 0.72421793  0.5581321   0.76266412 ... -1.01317326 -0.2769359
  -1.42343451]
 [ 0.45540512  0.50209506  0.16513963 ... -0.32279861 -0.80539437
  -0.89556104]
 [ 0.56792796  0.51195018 -0.05407003 ... -0.46119335 -0.8362401
  -0.88755806]]

In [26]:
x = standardized_data
y = ESR['Class']

In [27]:
print(x)
print(y)

[[-1.62585637 -0.84035602  1.28007215 ...  1.95249006  0.63602195
   2.44408311]
 [-1.96317524 -1.35933392  1.73118027 ...  0.90425099  0.13402758
   2.01184337]
 [-2.08416582 -1.78667094  3.54360232 ...  0.08363757  0.4363787
   2.03395875]
 ...
 [ 0.72421793  0.5581321   0.76266412 ... -1.01317326 -0.2769359
  -1.42343451]
 [ 0.45540512  0.50209506  0.16513963 ... -0.32279861 -0.80539437
  -0.89556104]
 [ 0.56792796  0.51195018 -0.05407003 ... -0.46119335 -0.8362401
  -0.88755806]]
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
2875    0.0
2876    0.0
2877    0.0
2878    0.0
2879    0.0
Name: Class, Length: 2880, dtype: float64

In [28]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,stratify=y,random_state=2)

# Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
clf1 = LogisticRegression()
clf1.fit(X_train, y_train)
X_trainning_data_prediction = clf1.predict(X_train)

acc_log_reg = round(accuracy_score(X_trainning_data_prediction, y_train)*100,2)
print ('The testing accuracy due to logistic regression',str(acc_log_reg) + ' %')


X_test_data_prediction = clf1.predict(X_test)
acc_log_reg = round(accuracy_score(X_test_data_prediction, y_test)*100,2)
print ('The trainning accuracy',str(acc_log_reg) + ' %')


input_data = (3569.1645502276033,2063.8927540442164,1.6737259062456604,4.4447362906722345,0.5262086374136803,3.002088408715654,1.4250222149628013,3.3027389168677366,3563.80388774546,2060.239056808996,1.4040886882722885,2.279397625142047,1.2974008089347138,1.9600794414562057,0.7599563291241991,2.038976574144329,3709.0097120740693,2180.647682250679,19.491141388448067,39.84741942148074,20.493347999809618,41.2287964967144,46.00737210152773,73.49323257253741,3567.3652646503615,2062.4830972223294,1.2099963401875848,1.7718110277795354,0.16179325941076056,1.8184903572236792,0.6886717276621478,1.6417666169862315,3559.2192789568667,2057.363361163637,1.0275509554011428,2.5023887847525996,1.495156498646184,2.207700901706084,1.029114118297356,2.226548713744709,3677.92120815544,2159.747917973448,16.56418429067598,37.75394248650719,14.79399147039043,39.01913400137683,45.198246443440205,72.94291494925437,3574.9853368311283,2066.285516719386,1.024091979410101,2.980396263615955,0.9616119083522146,2.6522677130112546,3.595956730908903,5.876658118715367,3641.1855276249125,2147.591861938904,24.949741498558545,49.475072884767826,20.62595751977841,47.43664660378428,46.813504716231044,76.56728379426937,3579.2685387320844,2077.123468939235,3.607672368919065,9.938368917187017,4.343275036101095,12.528566017422637,17.19451664142212,27.690241735191368,3636.780856395662,2138.663492934993,19.3106698404085,36.20083571404867,15.881326556552738,38.774852645918465,43.60199502020086,69.778362729039,3694.245877472315,2174.777021196275,18.42652422355754,40.4883929319332,16.41050498199057,38.85033552451535,45.32926324514407,72.90779981468211,3577.5214338152978,2067.996961866034,1.2329730962348122,3.073659235927023,0.9194189952153057,2.634124325509432,3.3486977417075225,5.380652423380749,3665.336755373622,2157.675046311957,15.543111488507492,37.37419935494729,15.907311987132736,40.854795335375655,45.468325549548254,72.50874980453948,3701.186330401986,2182.676835001596,18.19241807455738,41.349662145306006,16.004755565937725,42.04646727404781,46.2808430260123,73.5657188422982)
input_data_as_numpy_array = np.asarray(input_data)
#reshape the array as we predicting for one instance
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

#standardize the input data
std_data = sc.transform(input_data_reshape)
print(std_data)

prediction = clf1.predict(std_data)
print(prediction)

if (prediction[0] == 0):
    print("The person in thinking neutral")
elif (prediction[0] == 1):
    print("The person is thinking right movement:")
elif(prediction[0] == 2):
    print("The person is thinking left movement:")

The testing accuracy due to logistic regression 70.14 %
The trainning accuracy 60.5 %
[[-1.62585637e+00 -8.40356016e-01  1.28007215e+00  2.04225344e+00
  -9.73768105e-01  8.96646128e-01 -1.40315057e+00 -2.17058387e-02
  -1.69115972e+00 -1.08266227e+00  1.20123314e+00  1.29392966e-01
   9.69290646e-01 -3.37551361e-01 -1.61491408e+00 -6.12382859e-01
   2.34023109e+00  1.92770699e+00  2.01120941e+00  1.33630399e+00
   2.07332752e+00  1.60947119e+00  4.63353609e-01  2.21513235e+00
   1.76075159e+00  2.05970640e+00  1.25382367e+00 -1.63760019e-02
  -1.58189592e+00 -3.06124723e-03 -1.09509526e+00 -5.63893382e-01
  -8.43298637e-01 -4.31042785e-01  5.78403423e-01  8.92138508e-01
   1.20283968e+00  7.47153491e-02  9.98703870e-02  7.62316468e-01
   2.14708286e+00  2.00757874e+00  2.02231308e+00  1.62116559e+00
   1.51849596e+00  1.90876426e+00  7.62345521e-01  2.74427796e+00
   8.97141880e-01  6.21314548e-01 -1.47755575e-01  4.69912255e-01
  -4.61268124e-01 -2.72627284e-01 -7.38379474e-01  4.24529429e-01
   1.67588579e+00  1.73691464e+00  2.93367532e+00  1.76222301e+00
   2.72963855e+00  2.38395200e+00  1.22193101e+00  2.90095043e+00
  -1.08501571e+00  4.82064335e-02  1.05853058e+00  1.41041781e+00
   9.90347306e-01  1.75558887e+00  1.00675181e+00  2.75775316e+00
   1.48882272e+00  1.82848275e+00  3.40678203e+00  2.06557178e+00
   2.59548877e+00  2.79115182e+00  1.47226686e+00  3.77458740e+00
   2.05444218e+00  1.88060065e+00  1.99632820e+00  1.53306815e+00
   1.58549617e+00  1.62703735e+00  5.67164417e-01  2.50607688e+00
   7.92651177e-02 -1.07645705e-01 -2.28086114e-01 -1.63802289e-01
  -5.31676513e-01 -3.22891186e-01 -1.81049380e-01  2.96221004e-01
   1.07020304e+00  1.51758316e+00  2.00409539e+00  1.79156752e+00
   1.99523374e+00  2.37462603e+00  1.06388430e+00  3.06213133e+00
   2.22687218e+00  2.23587122e+00  2.13212144e+00  1.72341056e+00
   1.53181595e+00  1.95249006e+00  6.36021948e-01  2.44408311e+00]]
[1.]
The person is thinking right movement:

C:\Users\USER\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

# Support Vector Machines (SVM)

In [30]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
clf2 = SVC()
clf2.fit(X_train, y_train)
X_training_svm = clf2.predict(X_train)
acc_svm = round(accuracy_score(X_training_svm, y_train) * 100, 2)
print (' training Accuracy due to svm',str(acc_svm) + '%')

##### testing accuracy

X_test_svm_prediction = clf2.predict(X_test)
acc_svm = round(accuracy_score(X_test_svm_prediction, y_test)*100,2)
print ('testing Accuracy due to svm',str(acc_svm) + ' %')

# predicting system 


input_data1 = (3571.5776698564637,2063.503373184418,0.6029205352726208,2.967502905177528,1.4389885333016486,3.295020474122926,2.052318300662066,3.1929348458678626,3563.866619628976,2060.286630465621,1.2048099804200265,2.8103413736129825,0.27225772874660253,3.2862951557027094,1.0678356137575986,1.9728319154162408,3652.2514313778815,2127.7279583112304,13.27429161159918,34.36241292717517,36.26740246352244,56.93358683986829,48.214204584167035,74.47805088211938,3567.9662227438766,2061.7293157396007,0.5639959873004751,1.8721454702989053,1.4744399511095823,3.151339493976347,1.1046383080327566,1.9720318177527565,3557.726002755468,2055.8270423349927,0.891967376033974,2.669653114283589,1.5092077923923408,3.223965144639929,1.1366182390371824,2.1194584472732623,3629.0269092328194,2112.43573527682,13.547810600175742,33.42932882710743,32.38408386460878,56.56392200821375,46.852538109751684,75.99428250396319,3572.7670294266136,2064.8107935615335,1.1138945552313306,3.087238282060807,2.594065151630992,3.6937640590190437,3.743236375279487,5.449513343688413,3624.6588025440947,2117.797875892098,17.72209210101678,44.826561263290984,45.20186494044083,70.46932926197067,52.01336589318217,78.6992320452235,3574.8087842736973,2069.4394015495755,3.9431400426464016,10.523827732442765,9.784315414140655,16.80055893338254,16.40704563679004,29.77800027885906,3599.12334525423,2092.832289859586,10.32278916169577,31.94580621129784,27.862453555402396,51.41803859432595,42.988782306876445,69.05913364184316,3644.8426227370746,2124.2769771486005,13.791168423040311,35.1227944717199,35.803994796177,52.92858607598883,47.091113299675946,75.77059064746959,3574.582758813449,2065.692541804272,0.9280601508137211,2.6745293039707225,1.7775098800923772,3.4632397601696416,3.531847362428501,4.635422446750105,3612.975093711585,2106.3912922348186,10.486696520513933,34.594568511354616,31.14109960070707,57.91657781776544,46.74556734516573,76.699566475851,3687.0169057606745,2147.3154736112638,11.454735106178045,34.232922759264135,35.43148877248333,58.78652499474915,48.76385063044414,77.23551806293348)
input_data_as_numpy_array1 = np.asarray(input_data1)
#reshape the array as we predicting for one instance
input_data_reshape1 = input_data_as_numpy_array1.reshape(1,-1)

#standardize the input data
std_data1 = sc.transform(input_data_reshape1)
print(std_data1)

prediction1 = clf2.predict(std_data1)
print(prediction1)

if (prediction1[0] == 0):
    print("The person in thinking neutral")
elif (prediction1[0] == 1):
    print("The person is thinking right movement:")
elif(prediction1[0] == 2):
    print("The person is thinking left movement:")

 training Accuracy due to svm 86.28%
testing Accuracy due to svm 74.22 %
[[-0.52717507 -1.0950233  -0.87578107  0.50888045  1.12458942  1.27649297
  -0.30169706 -0.29994166 -1.65710681 -1.04100448  0.71152563  0.98200958
  -1.60275348  2.03292817 -0.63533153 -0.85720046  1.00831323  0.52983351
   0.98009369  0.99050538  4.66883365  2.80584085  0.60799547  2.2837932
   2.02482062  1.59526546 -0.48798684  0.14346213  1.88488058  2.12521597
   0.08749169  0.15585583 -1.4757291  -1.45532389  0.22120032  1.16182443
   1.23282377  1.57962549  0.4917074   0.49786333  0.82313485  0.47963317
   1.42414549  1.29799462  4.94752087  3.49082729  0.87439168  2.97372804
  -0.1302417  -0.50687597  0.03471128  0.61345484  2.56873352  0.96155227
  -0.58904021  0.04750534  1.28076451  1.00318576  1.91011487  1.5497353
   6.80049491  3.87072022  1.44084562  3.00671922 -1.63700691 -1.33828245
   1.31739089  1.60062998  4.35099316  3.07237575  0.81130387  3.21119363
   0.49532767  0.26627403  1.29969486  1.69853138  5.48782526  4.16673654
   1.42081204  3.70977571  0.86116248  0.48162201  1.18529016  1.17063022
   5.04315456  2.78893476  0.68988494  2.72323812 -0.04095073 -0.22582486
  -0.55515949 -0.32456377  0.73943689  0.24259729 -0.04789922 -0.16523636
  -0.28954566 -0.1856575   0.95834972  1.57166527  5.12875764  3.99031222
   1.15571019  3.38720028  1.88979775  1.19101036  0.88379449  1.21964255
   4.95419066  3.34345383  0.79744876  2.70430569]]
[1.]
The person is thinking right movement:

C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

# ################################################################

# K-Nearest Neighbour

In [31]:
from sklearn.neighbors import KNeighborsClassifier
clf3 = KNeighborsClassifier()
clf3.fit(X_train, y_train)
X_training_knn = clf3.predict(X_train)
acc_knn = round(accuracy_score(X_training_knn, y_train) * 100, 2)
print ('training  accuracy due to k-nearest neighbors',str(acc_knn)+'%')

X_test_knn_prediction = clf3.predict(X_test)
acc_knn = round(accuracy_score(X_test_knn_prediction, y_test)*100,2)
print ('Testing accuracy due to k-nearest neighbors',str(acc_knn) + ' %')


input_data2 = (3571.5776698564637,2063.503373184418,0.6029205352726208,2.967502905177528,1.4389885333016486,3.295020474122926,2.052318300662066,3.1929348458678626,3563.866619628976,2060.286630465621,1.2048099804200265,2.8103413736129825,0.27225772874660253,3.2862951557027094,1.0678356137575986,1.9728319154162408,3652.2514313778815,2127.7279583112304,13.27429161159918,34.36241292717517,36.26740246352244,56.93358683986829,48.214204584167035,74.47805088211938,3567.9662227438766,2061.7293157396007,0.5639959873004751,1.8721454702989053,1.4744399511095823,3.151339493976347,1.1046383080327566,1.9720318177527565,3557.726002755468,2055.8270423349927,0.891967376033974,2.669653114283589,1.5092077923923408,3.223965144639929,1.1366182390371824,2.1194584472732623,3629.0269092328194,2112.43573527682,13.547810600175742,33.42932882710743,32.38408386460878,56.56392200821375,46.852538109751684,75.99428250396319,3572.7670294266136,2064.8107935615335,1.1138945552313306,3.087238282060807,2.594065151630992,3.6937640590190437,3.743236375279487,5.449513343688413,3624.6588025440947,2117.797875892098,17.72209210101678,44.826561263290984,45.20186494044083,70.46932926197067,52.01336589318217,78.6992320452235,3574.8087842736973,2069.4394015495755,3.9431400426464016,10.523827732442765,9.784315414140655,16.80055893338254,16.40704563679004,29.77800027885906,3599.12334525423,2092.832289859586,10.32278916169577,31.94580621129784,27.862453555402396,51.41803859432595,42.988782306876445,69.05913364184316,3644.8426227370746,2124.2769771486005,13.791168423040311,35.1227944717199,35.803994796177,52.92858607598883,47.091113299675946,75.77059064746959,3574.582758813449,2065.692541804272,0.9280601508137211,2.6745293039707225,1.7775098800923772,3.4632397601696416,3.531847362428501,4.635422446750105,3612.975093711585,2106.3912922348186,10.486696520513933,34.594568511354616,31.14109960070707,57.91657781776544,46.74556734516573,76.699566475851,3687.0169057606745,2147.3154736112638,11.454735106178045,34.232922759264135,35.43148877248333,58.78652499474915,48.76385063044414,77.23551806293348)
input_data_as_numpy_array2 = np.asarray(input_data2)
#reshape the array as we predicting for one instance
input_data_reshape2 = input_data_as_numpy_array2.reshape(1,-1)

#standardize the input data
std_data2 = sc.transform(input_data_reshape2)
print(std_data2)

prediction2 = clf3.predict(std_data2)
print(prediction2)

if (prediction2[0] == 0):
    print("The person in thinking neutral")
elif (prediction2[0] == 1):
    print("The person is thinking right movement:")
elif(prediction2[0] == 2):
    print("The person is thinking left movement:")

training  accuracy due to k-nearest neighbors 92.19%
Testing accuracy due to k-nearest neighbors 82.38 %
[[-0.52717507 -1.0950233  -0.87578107  0.50888045  1.12458942  1.27649297
  -0.30169706 -0.29994166 -1.65710681 -1.04100448  0.71152563  0.98200958
  -1.60275348  2.03292817 -0.63533153 -0.85720046  1.00831323  0.52983351
   0.98009369  0.99050538  4.66883365  2.80584085  0.60799547  2.2837932
   2.02482062  1.59526546 -0.48798684  0.14346213  1.88488058  2.12521597
   0.08749169  0.15585583 -1.4757291  -1.45532389  0.22120032  1.16182443
   1.23282377  1.57962549  0.4917074   0.49786333  0.82313485  0.47963317
   1.42414549  1.29799462  4.94752087  3.49082729  0.87439168  2.97372804
  -0.1302417  -0.50687597  0.03471128  0.61345484  2.56873352  0.96155227
  -0.58904021  0.04750534  1.28076451  1.00318576  1.91011487  1.5497353
   6.80049491  3.87072022  1.44084562  3.00671922 -1.63700691 -1.33828245
   1.31739089  1.60062998  4.35099316  3.07237575  0.81130387  3.21119363
   0.49532767  0.26627403  1.29969486  1.69853138  5.48782526  4.16673654
   1.42081204  3.70977571  0.86116248  0.48162201  1.18529016  1.17063022
   5.04315456  2.78893476  0.68988494  2.72323812 -0.04095073 -0.22582486
  -0.55515949 -0.32456377  0.73943689  0.24259729 -0.04789922 -0.16523636
  -0.28954566 -0.1856575   0.95834972  1.57166527  5.12875764  3.99031222
   1.15571019  3.38720028  1.88979775  1.19101036  0.88379449  1.21964255
   4.95419066  3.34345383  0.79744876  2.70430569]]
[1.]
The person is thinking right movement:

C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [32]:
!pip install --upgrade tabulate

Requirement already satisfied: tabulate in c:\users\user\anaconda3\lib\site-packages (0.8.10)

In [33]:
!pip install --upgrade simple_colors

Requirement already satisfied: simple_colors in c:\users\user\anaconda3\lib\site-packages (0.1.5)

In [34]:
# import module
from tabulate import tabulate
from simple_colors import *
# assign data
mydata = [
[black('K NEAREST NEIGHBORS','bold'),black(round(accuracy_score(X_test_knn_prediction,y_test)*100,2),'bold')],
[black('SUPPORT VECTOR MACHINES','bold'),black(round(accuracy_score(X_test_svm_prediction, y_test)*100,2),'bold')],
[black('LOGISTIC REGRESSION','bold'),black(round(accuracy_score(X_test_data_prediction, y_test)*100,2),'bold')]
]

# create header

head = [(red('Classifier','bold')),(red('Accuracy(%)','bold')),'\033[1m']
'Accuracy(%)'
# display table
print(tabulate(mydata, headers=head, tablefmt="grid"))

+-------------------------+---------------+
| Classifier              |   Accuracy(%) |
+=========================+===============+
| K NEAREST NEIGHBORS     |         82.38 |
+-------------------------+---------------+
| SUPPORT VECTOR MACHINES |         74.22 |
+-------------------------+---------------+
| LOGISTIC REGRESSION     |         60.5  |
+-------------------------+---------------+