In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

In [2]:
dataset=pd.read_csv('user_c.csv')
dataset.head()

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3573.336166,2067.827798,1.334973,2.294574,0.742210,2.052755,3.604952,4.854279,3575.508401,...,3.625333,8.860455,3522.728728,2045.497490,0.750616,2.170167,1.372258,2.098884,2.418585,3.885361
1,1.0,3569.424197,2063.871329,1.639684,2.573080,1.097168,2.678287,2.313650,4.727548,3573.524571,...,3.918033,7.473774,3526.382257,2047.897934,0.799930,2.408514,1.110604,2.154791,2.048773,4.238736
2,1.0,3570.767652,2064.654687,0.706498,2.613442,1.086770,2.222977,2.409857,4.936480,3573.935350,...,4.355499,8.318612,3531.725098,2049.223458,1.411546,2.642449,1.518919,1.738234,1.457515,3.860666
3,1.0,3569.156909,2065.357831,0.940101,2.563546,0.836405,2.151778,2.650254,4.500677,3572.802320,...,3.683768,5.963362,3529.415919,2049.231604,1.221492,3.438005,1.272858,2.111202,1.679218,3.506380
4,1.0,3567.536119,2063.997440,0.961830,2.374021,1.046514,1.783034,2.432391,4.626892,3571.437750,...,3.498479,6.482901,3519.874261,2044.473685,1.797157,3.386036,0.770980,3.505291,1.477401,3.687515

In [4]:
dataset

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3573.336166,2067.827798,1.334973,2.294574,0.742210,2.052755,3.604952,4.854279,3575.508401,...,3.625333,8.860455,3522.728728,2045.497490,0.750616,2.170167,1.372258,2.098884,2.418585,3.885361
1,1.0,3569.424197,2063.871329,1.639684,2.573080,1.097168,2.678287,2.313650,4.727548,3573.524571,...,3.918033,7.473774,3526.382257,2047.897934,0.799930,2.408514,1.110604,2.154791,2.048773,4.238736
2,1.0,3570.767652,2064.654687,0.706498,2.613442,1.086770,2.222977,2.409857,4.936480,3573.935350,...,4.355499,8.318612,3531.725098,2049.223458,1.411546,2.642449,1.518919,1.738234,1.457515,3.860666
3,1.0,3569.156909,2065.357831,0.940101,2.563546,0.836405,2.151778,2.650254,4.500677,3572.802320,...,3.683768,5.963362,3529.415919,2049.231604,1.221492,3.438005,1.272858,2.111202,1.679218,3.506380
4,1.0,3567.536119,2063.997440,0.961830,2.374021,1.046514,1.783034,2.432391,4.626892,3571.437750,...,3.498479,6.482901,3519.874261,2044.473685,1.797157,3.386036,0.770980,3.505291,1.477401,3.687515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3564.428808,2061.273692,1.160073,3.096624,1.175471,2.279274,2.315288,4.024737,3573.155032,...,4.810416,7.566486,3549.920882,2061.561732,1.387117,2.540081,1.308723,3.040567,1.871892,2.614278
2876,0.0,3564.697729,2061.286621,1.906785,3.345629,1.139723,1.997279,2.501769,4.098686,3572.140438,...,4.633538,8.122404,3561.341949,2071.160307,0.674662,3.976616,2.300431,2.085824,1.376192,2.819355
2877,0.0,3567.845929,2063.314186,1.453872,2.585592,0.755025,2.538272,2.242644,4.315105,3572.306073,...,5.908094,8.588248,3574.189217,2080.610604,1.481339,5.599471,1.391585,3.285971,1.112041,3.016844
2878,0.0,3570.924216,2065.003367,1.014134,2.403987,0.472212,2.246067,2.863801,3.882231,3572.297011,...,5.132640,8.222525,3592.290042,2086.162688,0.569881,4.449971,0.502776,2.399818,1.209944,2.880771
2879,0.0,3573.119301,2066.337280,1.454676,2.247903,0.807849,1.962212,2.661367,3.792707,3572.587897,...,4.838910,7.138683,3603.653990,2088.993714,0.736759,1.445527,1.359783,1.984856,1.562745,2.616149

In [5]:
dataset.columns

Index(['Class', 'AF3 delta std', 'AF3 delta m', 'AF3 theta std', 'AF3 theta m',
       'AF3 alpha std', 'AF3 alpha m', 'AF3 beta std', 'AF3 beta m',
       'F7 delta std',
       ...
       'F8 beta std', 'F8 beta m', 'AF4 delta std', 'AF4 delta m',
       'AF4 theta std', 'AF4 theta m', 'AF4 alpha std', 'AF4 alpha m',
       'AF4 beta std', 'AF4 beta m'],
      dtype='object', length=113)

In [6]:
dataset.isnull().sum()  #isnull().sum()  gives the sum of missing value in the data set or  nan values here in the data set

Class            0
AF3 delta std    0
AF3 delta m      0
AF3 theta std    0
AF3 theta m      0
                ..
AF4 theta m      0
AF4 alpha std    0
AF4 alpha m      0
AF4 beta std     0
AF4 beta m       0
Length: 113, dtype: int64

In [7]:
dataset.info() # gives the information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Columns: 113 entries, Class to AF4 beta m
dtypes: float64(113)
memory usage: 2.5 MB

In [8]:
dataset.tail(2881) #gives the entire description of the data set

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3573.336166,2067.827798,1.334973,2.294574,0.742210,2.052755,3.604952,4.854279,3575.508401,...,3.625333,8.860455,3522.728728,2045.497490,0.750616,2.170167,1.372258,2.098884,2.418585,3.885361
1,1.0,3569.424197,2063.871329,1.639684,2.573080,1.097168,2.678287,2.313650,4.727548,3573.524571,...,3.918033,7.473774,3526.382257,2047.897934,0.799930,2.408514,1.110604,2.154791,2.048773,4.238736
2,1.0,3570.767652,2064.654687,0.706498,2.613442,1.086770,2.222977,2.409857,4.936480,3573.935350,...,4.355499,8.318612,3531.725098,2049.223458,1.411546,2.642449,1.518919,1.738234,1.457515,3.860666
3,1.0,3569.156909,2065.357831,0.940101,2.563546,0.836405,2.151778,2.650254,4.500677,3572.802320,...,3.683768,5.963362,3529.415919,2049.231604,1.221492,3.438005,1.272858,2.111202,1.679218,3.506380
4,1.0,3567.536119,2063.997440,0.961830,2.374021,1.046514,1.783034,2.432391,4.626892,3571.437750,...,3.498479,6.482901,3519.874261,2044.473685,1.797157,3.386036,0.770980,3.505291,1.477401,3.687515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.0,3564.428808,2061.273692,1.160073,3.096624,1.175471,2.279274,2.315288,4.024737,3573.155032,...,4.810416,7.566486,3549.920882,2061.561732,1.387117,2.540081,1.308723,3.040567,1.871892,2.614278
2876,0.0,3564.697729,2061.286621,1.906785,3.345629,1.139723,1.997279,2.501769,4.098686,3572.140438,...,4.633538,8.122404,3561.341949,2071.160307,0.674662,3.976616,2.300431,2.085824,1.376192,2.819355
2877,0.0,3567.845929,2063.314186,1.453872,2.585592,0.755025,2.538272,2.242644,4.315105,3572.306073,...,5.908094,8.588248,3574.189217,2080.610604,1.481339,5.599471,1.391585,3.285971,1.112041,3.016844
2878,0.0,3570.924216,2065.003367,1.014134,2.403987,0.472212,2.246067,2.863801,3.882231,3572.297011,...,5.132640,8.222525,3592.290042,2086.162688,0.569881,4.449971,0.502776,2.399818,1.209944,2.880771
2879,0.0,3573.119301,2066.337280,1.454676,2.247903,0.807849,1.962212,2.661367,3.792707,3572.587897,...,4.838910,7.138683,3603.653990,2088.993714,0.736759,1.445527,1.359783,1.984856,1.562745,2.616149

In [9]:
dataset.loc[3] # it fetches the particular row  loc[row number]

Class               1.000000
AF3 delta std    3569.156909
AF3 delta m      2065.357831
AF3 theta std       0.940101
AF3 theta m         2.563546
                    ...
AF4 theta m         3.438005
AF4 alpha std       1.272858
AF4 alpha m         2.111202
AF4 beta std        1.679218
AF4 beta m          3.506380
Name: 3, Length: 113, dtype: float64

In [10]:
dataset.loc[3,"AF3 delta std"]

3569.1569087644643

In [11]:
dataset.loc[0:4] # to extract the particular portion of the data set

,Class,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m,AF3 beta std,AF3 beta m,F7 delta std,...,F8 beta std,F8 beta m,AF4 delta std,AF4 delta m,AF4 theta std,AF4 theta m,AF4 alpha std,AF4 alpha m,AF4 beta std,AF4 beta m
0,1.0,3573.336166,2067.827798,1.334973,2.294574,0.742210,2.052755,3.604952,4.854279,3575.508401,...,3.625333,8.860455,3522.728728,2045.497490,0.750616,2.170167,1.372258,2.098884,2.418585,3.885361
1,1.0,3569.424197,2063.871329,1.639684,2.573080,1.097168,2.678287,2.313650,4.727548,3573.524571,...,3.918033,7.473774,3526.382257,2047.897934,0.799930,2.408514,1.110604,2.154791,2.048773,4.238736
2,1.0,3570.767652,2064.654687,0.706498,2.613442,1.086770,2.222977,2.409857,4.936480,3573.935350,...,4.355499,8.318612,3531.725098,2049.223458,1.411546,2.642449,1.518919,1.738234,1.457515,3.860666
3,1.0,3569.156909,2065.357831,0.940101,2.563546,0.836405,2.151778,2.650254,4.500677,3572.802320,...,3.683768,5.963362,3529.415919,2049.231604,1.221492,3.438005,1.272858,2.111202,1.679218,3.506380
4,1.0,3567.536119,2063.997440,0.961830,2.374021,1.046514,1.783034,2.432391,4.626892,3571.437750,...,3.498479,6.482901,3519.874261,2044.473685,1.797157,3.386036,0.770980,3.505291,1.477401,3.687515

In [12]:
dataset.loc[0:4,"AF3 delta std"] # to extract only the values of particular  section of the data set and particular coloum

0    3573.336166
1    3569.424197
2    3570.767652
3    3569.156909
4    3567.536119
Name: AF3 delta std, dtype: float64

In [14]:
dataset.loc[0:4,["AF3 delta std","AF3 delta m"]] # to extend the coloums

   AF3 delta std  AF3 delta m
0    3573.336166  2067.827798
1    3569.424197  2063.871329
2    3570.767652  2064.654687
3    3569.156909  2065.357831
4    3567.536119  2063.997440

In [16]:
# for the slicing the coloums based on the names
dataset.loc[0:4,"AF3 delta std":"AF3 alpha m"] # to extend the coloums

,AF3 delta std,AF3 delta m,AF3 theta std,AF3 theta m,AF3 alpha std,AF3 alpha m
0,3573.336166,2067.827798,1.334973,2.294574,0.742210,2.052755
1,3569.424197,2063.871329,1.639684,2.573080,1.097168,2.678287
2,3570.767652,2064.654687,0.706498,2.613442,1.086770,2.222977
3,3569.156909,2065.357831,0.940101,2.563546,0.836405,2.151778
4,3567.536119,2063.997440,0.961830,2.374021,1.046514,1.783034

In [17]:
dataset.iloc[:,1] # iloc[rows,coloudataset

0       3573.336166
1       3569.424197
2       3570.767652
3       3569.156909
4       3567.536119
           ...
2875    3564.428808
2876    3564.697729
2877    3567.845929
2878    3570.924216
2879    3573.119301
Name: AF3 delta std, Length: 2880, dtype: float64

In [18]:
l = [1,2,3,4]
l[:3]

[1, 2, 3]

In [19]:
x = dataset.iloc[:,1:113].values #take the values of the x to train
x
x.shape

(2880, 112)

In [20]:
y = dataset.iloc[:,0].values
y
y.shape
y

array([1., 1., 1., ..., 0., 0., 0.])

In [21]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state=0)

In [22]:
X_train

array([[3.57418895e+03, 2.06835071e+03, 1.26217061e+00, ...,
        5.73168041e+00, 1.63905888e+00, 3.52667710e+00],
       [3.56761255e+03, 2.06426239e+03, 1.49918868e+00, ...,
        1.82603948e+00, 2.48206027e+00, 3.05149685e+00],
       [3.57255908e+03, 2.06422291e+03, 5.72169462e-01, ...,
        2.62474121e+00, 1.71061567e+00, 3.17967288e+00],
       ...,
       [3.56538300e+03, 2.06177834e+03, 1.39868138e+00, ...,
        2.20829492e+00, 2.12705699e+00, 3.16559402e+00],
       [3.58333164e+03, 2.07158747e+03, 1.35181138e-01, ...,
        1.99217752e+00, 1.54791004e+00, 2.42377296e+00],
       [3.57500622e+03, 2.06666867e+03, 2.67779864e+00, ...,
        3.09472634e+00, 1.43528768e+00, 2.71827693e+00]])

In [23]:
X_test

array([[3.56170749e+03, 2.05829587e+03, 6.26578452e-01, ...,
        3.42957423e+00, 1.23877008e+00, 2.90659091e+00],
       [3.57032274e+03, 2.06586856e+03, 9.58419235e-01, ...,
        5.32298609e+00, 2.00191657e+00, 3.50704292e+00],
       [3.57280875e+03, 2.06600841e+03, 1.46783660e+00, ...,
        1.48348012e+00, 1.12804982e+00, 2.13684910e+00],
       ...,
       [3.57218849e+03, 2.06505122e+03, 8.84089288e-01, ...,
        2.03547839e+00, 1.67188261e+00, 3.04091103e+00],
       [3.57165954e+03, 2.06574149e+03, 1.52850592e+00, ...,
        2.38409782e+00, 1.65665955e+00, 2.99677273e+00],
       [3.57094251e+03, 2.06295029e+03, 1.51382296e+00, ...,
        2.87691853e+00, 1.27594830e+00, 2.30973930e+00]])

In [24]:
y_test

array([1., 0., 1., ..., 0., 2., 2.])

In [25]:
y_train

array([1., 2., 1., ..., 2., 2., 0.])

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# logistic regression

In [27]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression()


clf1.fit(X_train, y_train)
y_pred_log_reg = clf1.predict(X_test)
acc_log_reg = round(clf1.score(X_train, y_train) * 100, 2)
print (str(acc_log_reg) + ' %')

# Set regularization rate
reg = 1
# train a logistic regression model on the training set
model0 = LogisticRegression(C=0.1/reg, solver="liblinear").fit(X_train, y_train)
print (model0)

predictions0 = model0.predict(X_test)
print('Predicted labels: ', predictions0)
print('Actual labels:    ' ,y_test)


from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions0)*100,'%')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

61.4 %
LogisticRegression(C=0.1, solver='liblinear')
Predicted labels:  [2. 0. 1. ... 2. 2. 0.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 50.260416666666664 %

# support vector machines

In [28]:
#Support Vector Machine (SVM)
from sklearn.svm import SVC
clf2 = SVC()
clf2.fit(X_train, y_train)
y_pred_svc = clf2.predict(X_test)
acc_svc = round(clf2.score(X_train, y_train) * 100, 2)
print ('Accuracy due to svm',str(acc_svc) + '%')
#acc_svc =str(acc_svc )

# Set regularization rate
reg = 1
# train a support vector machine model on the training set
svm = SVC(kernel= 'linear', random_state=1, C=0.1)
svm.fit(X_train, y_train)
print (svm)

predictions1 = svm.predict(X_test)
print('Predicted labels: ', predictions1)
print('Actual labels:    ' ,y_test)

from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions1)*100,'%')

Accuracy due to svm 82.0%
SVC(C=0.1, kernel='linear', random_state=1)
Predicted labels:  [2. 0. 1. ... 0. 2. 0.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 50.43402777777778 %

# k nearest neighbors

In [29]:
#k-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
clf3 = KNeighborsClassifier()
clf3.fit(X_train, y_train)
y_pred_knn = clf3.predict(X_test)
acc_knn = round(clf3.score(X_train, y_train) * 100, 2)
print ('accuracy due to k-nearest neighbors',str(acc_knn)+'%')

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

predictions2 =classifier.predict(X_test)
print('Predicted labels: ', predictions2)
print('Actual labels:    ' ,y_test)

from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions2)*100,'%')

accuracy due to k-nearest neighbors 82.0%
Predicted labels:  [1. 0. 1. ... 0. 0. 2.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 67.44791666666666 %

# pickle model linear regression

In [30]:
#linear regression model 

import pickle
with open ('liner_model','wb') as f:
    pickle.dump(clf1,f)
    
with open('liner_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)

array([2., 0., 1., ..., 2., 2., 2.])

# joblib model linear regression

In [31]:
import joblib

joblib.dump(clf1,'linearmodel_joblib')
lin = joblib.load('linearmodel_joblib')
lin.predict(X_test)

array([2., 0., 1., ..., 2., 2., 2.])

# pickle model support vector machine

In [32]:
import pickle
with open ('svm_model','wb') as f1:
    pickle.dump(clf2,f1)
    
with open('svm_model','rb') as f1:
    np = pickle.load(f1)
    
np.predict(X_test)

array([2., 0., 1., ..., 0., 2., 2.])

# joblib model for k nearest neighbour

In [33]:
import joblib

joblib.dump(clf3,'knnmodel_joblib')
svm = joblib.load('knnmodel_joblib')
svm.predict(X_test)

array([1., 0., 1., ..., 0., 0., 2.])